7 спринт, 1 итерация.
DevDanila/java-kanban pull request #3
Opened 2024-12-01 18:27 UTC by DevDanila

Выполнено ТЗ 7 спринта.

2024-12-02 16:56 UTC, andrew-larkin requested changes
Привет! Основная часть сделана, но требуются некоторые доработки. Также, не хватает тестов для нового менеджера.

2024-12-02 16:56 UTC, andrew-larkin commented on src/com/practicum/java_kanban/manager/FileBackedTaskManager.java
> +		String fileName = ".src\\com\\practicum\\java_kanban\\manager\\dataFile.csv";
не стоит хардкодить местоположение файла. мы можем передавать его в file данного конструктора - new FileBackedTaskManager(new File("tasks.csv"")). обрати внимание, что если файла такого нет, он создастся автоматически в папке

2024-12-02 16:56 UTC, andrew-larkin commented on src/com/practicum/java_kanban/manager/FileBackedTaskManager.java
> +	public void save() throws ManagerSaveException {
private, т.к. метод должен использоваться только в этом классе

2024-12-02 16:56 UTC, andrew-larkin commented on src/com/practicum/java_kanban/manager/FileBackedTaskManager.java
> +	private String toString(Task task) {
все эти методы парсинга стоит сделать статическими и выделить в отдельный класс, например, CSVFormat. Это разгрузит текущий класс менеджера от доп. логики

2024-12-02 16:56 UTC, andrew-larkin commented on src/com/practicum/java_kanban/manager/InMemoryTaskManager.java
> +	final Map<Integer, Task> tasks = new HashMap<>();
неее) тогда уж сделать protected

2024-12-02 16:56 UTC, andrew-larkin commented on src/com/practicum/java_kanban/model/TaskType.java
> +
не могу оставить комментарий в классе Task, поэтому напишу его тут: в параметрах конструктора не надо передавать статус. когда мы используем конструктор, мы создаем задачу, а значит у нее всегда будет статус NEW. соответственно в конструкторе мы можем это написать как this.status = Status.NEW;

2024-12-03 17:33 UTC, DevDanila commented on src/com/practicum/java_kanban/model/TaskType.java
> +
Подправил конструктор и убрал статус из его параметров.

2024-12-03 17:34 UTC, DevDanila commented on src/com/practicum/java_kanban/manager/InMemoryTaskManager.java
> +	final Map<Integer, Task> tasks = new HashMap<>();
Блин я в прошлый раз делал все протектид, а Яков сказал вернуть все приват xDDDD

2024-12-03 17:36 UTC, DevDanila commented on src/com/practicum/java_kanban/manager/InMemoryTaskManager.java
> +	final Map<Integer, Task> tasks = new HashMap<>();
Сделал протектид.

2024-12-04 17:39 UTC, DevDanila commented on src/com/practicum/java_kanban/manager/FileBackedTaskManager.java
> +		String fileName = ".src\\com\\practicum\\java_kanban\\manager\\dataFile.csv";
Исправил конструктор.

2024-12-04 17:41 UTC, DevDanila commented on src/com/practicum/java_kanban/manager/FileBackedTaskManager.java
> +	public void save() throws ManagerSaveException {
сделал private

2024-12-07 13:43 UTC, DevDanila commented on src/com/practicum/java_kanban/manager/FileBackedTaskManager.java
> +	private String toString(Task task) {
Выделил методы в отдельный класс.

2024-12-08 12:55 UTC, merged